name: Deploy to GitHub Pages

on:
  push:
    branches:
      - dev  # Change this to the branch you use for development

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Adjust the version as needed

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build and Export
        run: npm run predeploy

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          publish_dir: ./out